# experiment_config.yaml: settings related to the experiment being run when the run.py script is launched,
# any custom session variables you want displayed in a dialog for input at the start of the experiment,
# and settings related to the local process the experiment run.py is launched in.
#

title: startingTemplate
code: strtTmp
version: '1.0'
description: Blank Starting Template
session_defaults:
    name: Session Name
    code: E1S01
    comments: None
    user_variables:
        participant_age: Unknown
        participant_gender: [ Select, Male, Female ]
        glasses: [Select, Yes, No ]
        contacts: [Select, Yes, No ]
session_variable_order: [ name, code, comments, participant_age, participant_gender, glasses, contacts ]
event_buffer_length: 2048
process_affinity: []
remaining_processes_affinity: []
ioHub:
    enable: True
    process_affinity: []
    config: iohub_config.yaml
  
