eyetracker.hw.tobii.EyeTracker:
    name: 
        IOHUB_STRING:
            min_length: 1
            max_length: 32
            first_char_alpha: True
    enable: IOHUB_BOOL
    model_name:
        IOHUB_LIST:
            valid_values: [Tobii T120, None]
            min_length: 0
            max_length: 1
    serial_number:
        IOHUB_STRING:
            min_length: 0
            max_length: 32
    manufacturer_name: Tobii Technology
    save_events: IOHUB_BOOL
    stream_events: IOHUB_BOOL
    auto_report_events: False
    event_buffer_length: 
        IOHUB_INT:
            min: 1
            max: 2048
    monitor_event_types:           
        IOHUB_LIST:
            valid_values: [ BinocularEyeSampleEvent, ]
            min_length: 1
            max_length: 1
    runtime_settings:
        sampling_rate: [25,30,60,120,400]
        track_eyes: [BINOCULAR,]
    calibration:
        # The Tobii ioHub Common Eye Tracker Interface currently support 
        # a 3, 5 and 9 point calibration mode.
        # THREE_POINTS,FIVE_POINTS,NINE_POINTS
        type: [THREE_POINTS,FIVE_POINTS,NINE_POINTS]
        randomize: False
        target_positions: []
        auto_pace: IOHUB_BOOL
        pacing_speed:
            IOHUB_FLOAT:
                min: 0.5
                max: 2.5
        screen_background_color: IOHUB_RGBA255_COLOR
        target_type: [CIRCLE_TARGET,]
        target_attributes:
            outer_diameter:
                IOHUB_INT:
                    min: 8
                    max: 256
            inner_diameter: 
                IOHUB_INT:
                    min: 0
                    max: 255
            outer_color: IOHUB_RGBA255_COLOR
            inner_color: IOHUB_RGBA255_COLOR                 
    device_number: 0
    manufacture_date: IOHUB_DATE
    model_number:
        IOHUB_STRING:
            min_length: 1
            max_length: 16
    software_version:
        IOHUB_STRING:
            min_length: 1
            max_length: 8    
    hardware_version: 
        IOHUB_STRING:
            min_length: 1
            max_length: 8
    firmware_version: 
        IOHUB_STRING:
            min_length: 1
            max_length: 8