# iohub_config.yaml: settings related to the iohub process and the device types that are to be enabled for the
# experiment. 

monitor_devices:
    - Keyboard:
        name: kb
        saveEvents: True
        streamEvents: True
        event_buffer_length: 256
    - Mouse:
        name: mouse
        saveEvents: True
        streamEvents: True
        event_buffer_length: 256
    - ExperimentDevice:
        name: experimentRuntime
        saveEvents: True
        streamEvents: True
        event_buffer_length: 64
    - Display: &DisplaySettings
        name: display
        reporting_unit_type: pixels
        display_index: 0
        physical_stimulus_area:
            width: 500
            height: 281
            unit_type: mm
        default_eye_to_surface_distance:
            surface_center: 500
            unit_type: mm
        psychopy_config_file: default
    - eyetracker.HW.SR_Research.EyeLink.EyeTracker:
        #device_class: eyetracker.HW.SMI.iViewX.EyeTracker
        enable: True
        name: tracker
        saveEvents: True
        streamEvents: True
        device_timer:
            interval: 0.001
        event_buffer_length: 1024
        display_settings: *DisplaySettings
        runtime_settings:
            sampling_rate: 250
            track_eyes: LEFT
            default_calibration: HV9
            auto_calibration: True
            auto_calibration_speed: 1.5
            runtime_filtering:
                ALL: OFF
            enable_api_without_connection: False
            network_settings: 100.1.1.1
            default_native_data_file_name: et_data
            vog_settings:
                pupil_measure_types: DIAMETER
                tracking_mode: PUPIL-CR
                pupil_center_algorithm: CENTROID
ioDataStore:
    enable: True