# iohub_config.yaml: settings related to the iohub process and the device types that are to be enabled for the
# experiment.
monitor_devices:
    - Display:
        name: display
        reporting_unit_type: deg

        device_number: 0
        # T120 monitor size
        physical_dimensions:
            width: 600
            height: 340
            unit_type: mm
        default_eye_distance:
            surface_center: 600
            unit_type: mm
        origin: center
        psychopy_monitor_name: default
    - Keyboard:
        name: kb
        save_events: True
        stream_events: True
    - Mouse:
        name: mouse
        save_events: True
        stream_events: True
    - Experiment:
        name: experimentRuntime
        enable: True
        save_events: True
        stream_events: True
data_store:
    enable: True
