# Experiment level configuration settings in YAML format
title: ioHub XInput Gamepad Example with PsychoPy
code: ioXInput
version: '1.0'
description: Uses an XInput compatible gamepad within a psychoPy script.
session_defaults:
    name: Session Name
    code: E1S01
    comments: None
session_variable_order: [ name, code, comments ]
ioHub:
    enable: True
    config: ioHub_config.yaml
  
