# Experiment level configuration settings in YAML format
title: ioHub XInput Gamepad Example with PsychoPy
code: ioXInputPsychoPy
version: '1.0'
description: Uses an XInput compatible gamepad within a psychoPy script.
session_defaults:
    name: Session Name
    code: E1S01
    comments: None
    user_variables:
        participant_age: Unknown
        participant_gender: [ Select, Male, Female ]
        glasses: [Select, Yes, No ]
        contacts: [Select, Yes, No ]
session_variable_order: [ name, code, comments, participant_age, participant_gender, glasses, contacts ]
ioHub:
    enable: True
    config: ioHub_config.yaml
  
