# iohub_config.yaml: settings related to the iohub process and the device types 
# that are to be enabled for the experiment.

monitor_devices:
    - Keyboard:
        name: keyboard
        saveEvents: True
        streamEvents: True
        auto_report_events: True
        event_buffer_length: 256
    - Mouse:
        name: mouse
        saveEvents: True
        streamEvents: True
        auto_report_events: True
        event_buffer_length: 256
    - ExperimentDevice:
        name: experimentRuntime
        saveEvents: True
        streamEvents: True
        auto_report_events: True
        event_buffer_length: 64
    - GamePad:
        user_id: -1
        name: gamepad
        enable: True
        saveEvents: True
        streamEvents: True
        auto_report_events: True
        event_buffer_length: 256
        device_timer:
            interval: 0.001
    - Display: &DisplaySettings
        name: display
        reporting_unit_type: pixels
        display_index: 0
        physical_stimulus_area:
            width: 500
            height: 281
            unit_type: mm
        default_eye_to_surface_distance:
            surface_center: 500
            unit_type: mm
        display_pixel_origin: [0.5,0.5]
        psychopy_config_file: default
ioDataStore:
    enable: True