title: AnalogInput Example
code: ai_test
version: '1.0'
description: Displays values of 8 ch from AnalogInput Device
session_defaults:
    name: Session Name
    code: E1S01
    comments: None
    user_variables:
        participant_age: Unknown
        participant_gender: [ Select, Male, Female ]
        trial_count: [1,2,3,4,5,6,7,8,9,10]
session_variable_order: [ name, code, comments, participant_age, participant_gender, trial_count ]
  
