monitor_devices:
    - Display:
        name: display
        reporting_unit_type: pix
        device_number: 0
        physical_dimensions:
            width: 500
            height: 281
            unit_type: mm
        default_eye_distance:
            surface_center: 500
            unit_type: mm
        psychopy_monitor_name: ioDefault
        origin: center
    - Keyboard:
        name: kb
    - Mouse:
        name: mouse
    - Experiment:
        name: experimentRuntime
    - xinput.Gamepad:
        device_number: -1
        name: gamepad
        device_timer:
            interval: 0.005
data_store:
    enable: True
