# Experiment level configuration settings in YAML format
title: Simple Example with PsychoPy
code: simplx
version: '1.0'
description: Uses an Mouse to drive a Gaussian dot.
session_defaults:
    name: Session Name
    code: E1S01
    comments: None
session_variable_order: [ name, code, comments ]
ioHub:
    enable: True
    config: ioHub_config.yaml
  
