# iohub_config.yaml: settings related to the iohub process and the device types that are to be enabled for the
# experiment.
#
monitor_devices:
    - Display:
        name: display
        reporting_unit_type: pix
        device_number: 0
        physical_dimensions:
            width: 500
            height: 281
            unit_type: mm
        default_eye_distance:
            surface_center: 500
            unit_type: mm
        origin: center
        psychopy_monitor_name: default
    - Keyboard:
        name: kb
        save_events: True
        stream_events: True
        auto_report_events: True
        event_buffer_length: 256
    - Mouse:
        name: mouse
        save_events: True
        stream_events: True
        auto_report_events: True
        event_buffer_length: 256
    - Experiment:
        name: experimentRuntime
        save_events: True
        stream_events: True
        auto_report_events: True
        event_buffer_length: 128
data_store:
    enable: True
