# experiment_config.yaml: settings related to the experiment being run when the sequentialFixationTask.py
# script is launched, any custom session variables you want displayed in a dialog for input at the start
# of the experiment, and settings related to the local process the experiment simpleTrackerTest.py is launched in.
#
title: sequentialFixationTask
code: seqFixA
version: '0.1'
description: Implementation of the fixation sequence testing paradigm as a way to try out the ioHub.
session_defaults:
    name: Session Name
    code: E1S01
    comments: None
    user_variables:
        participant_age: Unknown
        participant_gender: [ Select, Male, Female ]
        glasses: False
        contacts: False
        eye_color: Unknown
session_variable_order: [ name, code, comments, participant_age, participant_gender, glasses, contacts, eye_color ]
paths:
    resources:
        condition_files: [[CONDITION_FILES], [xls]]
        images: [[IMAGE_FILES],[png]]
        audio: [[AUDIO_FILES],[flac, mp3]]
        video: [[VIDEO_FILES],[avi, mp4, mkv]]
    results:
        data_store: [[IOHUB_DATA],[hdf5]]
        sessions:
            session_defaults.code: [[LOGS,SYS_INFO,USER_FILES,NATIVE_DEVICE_DATA],[]]
process_affinity: []
remaining_processes_affinity: []
event_buffer_length: 1024
ioHub:
    enable: True
    process_affinity: []
    config: ioHub_config.yaml